### ISSUE TITLE
Can't locate jvm.dll

### ISSUE THREAD

**Issue by djpesic** [astonbitecode/java-locator#4]
I'm running windows 11, and I have installed Oracle JDK 21 and old jdk1.8.0_202 (for some legacy software I currently use and plan to modernize). I tried to test the tool and got error, when trying to find jvm.dll. This is necessary for using crate j4rs, which use java locator tool.
Command outputs:

```
C:\Users\djpes>java-locator.exe
WARNING: java_locator found 2 possible java locations: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe, C:\Program Files\Common Files\Oracle\Java\javapath\java.exe. Using the last one.
C:\Program Files\Common Files\Oracle\Java

C:\Users\djpes>java-locator.exe -j
WARNING: java_locator found 2 possible java locations: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe, C:\Program Files\Common Files\Oracle\Java\javapath\java.exe. Using the last one.
Error: JavaLocatorError { description: "Could not find the jvm.dll library in any subdirectory of C:\\Program Files\\Common Files\\Oracle\\Java" }
```
I also switched order of java paths inside system variable configuration, but again, can't find.

jvm.dll which I need for using j4rs is located at:
```
C:\Program Files\Java\jdk-21\bin\server
```

**Comment by astonbitecode** [comment]
I guess you have to set the env var `JAVA_HOME` pointing to the JRE/JDK you want to use. 

As I understand, you would actually like to set `JAVA_HOME` to `"C:\Program Files\Java\jdk-21"`. 

Please note that the characters `"` in the path above are intentional there because of the space existing in the path.

**Comment by djpesic** [comment]
Thanks for the hint. Additionally, I  used the "Browse directory" button in the window to add a new path. That was the only way to make the terminal recognize the JDK path. Typing the path manually don't work, even with ` " ` character typed.
